on:
  workflow_dispatch:
    
jobs:
  job1:
    runs-on: self-hosted
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Download
        uses: actions/checkout@v2
      - name: run script
        run: .\scripts\create_conan.ps1
      - uses: actions/upload-artifact@v3
      with:
        name: ansys.motion.post_api
        path: ansys.motion.post_api.zip